import Image from "next/image";
import Input from "react-select/dist/declarations/src/components/Input";

export default [
  {
    id: 1,
    program: "",
    kegiatan: "waani",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User1.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 2,
    program: "",
    kegiatan: "waan",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User2.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 3,
    program: "",
    kegiatan: "waa",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User3.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 4,
    program: "",
    kegiatan: "waa",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User3.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 5,
    program: "",
    kegiatan: "waa",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User3.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 6,
    program: "",
    kegiatan: "waa",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User3.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 7,
    program: "",
    kegiatan: "waa",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User3.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 8,
    program: "",
    kegiatan: "waa",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User3.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 9,
    program: "",
    kegiatan: "waa",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User3.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
  {
    id: 10,
    program: "",
    kegiatan: "waa",
    subKegiatan: "Money wrap",
    tupoksiinti: "rekonsiliasi",
    rekan: <Image src="/User3.svg" width={30} height={30} />,
    rencana: "jan-des",
    status: "sementara",
  },
];